return {
  -- Add the community repository of plugin specifications
  "AstroNvim/astrocommunity",
  -- { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.cpp" },
  { import = "astrocommunity.pack.rust" },
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.yaml" },
  -- { import = "astrocommunity.pack.godot" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.file-explorer.oil-nvim" },
  { import = "astrocommunity.completion.codeium-vim" },
  { import = "astrocommunity.utility.transparent-nvim" },
  { import = "astrocommunity.editing-support.chatgpt-nvim" },
  { import = "astrocommunity.motion.leap-nvim" },
  { import = "astrocommunity.editing-support.auto-save-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.utility.noice-nvim" },
  -- { import = "astrocommunity." },
}
